//! Development-only dock icon.
//!
//! macOS dev builds do not apply the Dock squircle mask automatically, so we load a
//! pre-masked PNG (`icons/icon-dock.png`) generated by `scripts/fix-macos-icon-source.py`.

#[cfg(all(debug_assertions, target_os = "macos"))]
pub fn set_dev_dock_icon() {
    use objc2::{AllocAnyThread, MainThreadMarker};
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::NSData;

    let icons = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("icons");
    let path = icons.join("icon-dock.png");

    let Ok(bytes) = std::fs::read(&path) else {
        eprintln!("[dev-icon] missing icon file: {}", path.display());
        return;
    };

    let mtm = unsafe { MainThreadMarker::new_unchecked() };
    let app = NSApplication::sharedApplication(mtm);
    let data = NSData::with_bytes(&bytes);
    let Some(icon) = NSImage::initWithData(NSImage::alloc(), &data) else {
        eprintln!("[dev-icon] failed to decode: {}", path.display());
        return;
    };
    unsafe {
        app.setApplicationIconImage(Some(&icon));
    }
}

#[cfg(not(all(debug_assertions, target_os = "macos")))]
pub fn set_dev_dock_icon() {}
